name: gee_demo
channels:
  - defaults
dependencies:
  - python=3.12
  - geopandas
  - matplotlib
  - numpy
  - optuna
  - pandas
  - scikit-learn
  - seaborn
  - jupyterlab
prefix: C:\Users\johnb\miniconda3\envs\gee_demo
